import { School } from "@/types/single-school";

const data: School[] = [
  {
    id: "1",
    name: "Greenwood High School",
    category: "Secondary",
    product: "EduSuite",
    county: "Greenwood County",
    registrationDate: new Date("2020-06-15"),
    contactInfo: {
      phone: "555-1234",
      email: "contact@greenwoodhigh.edu",
    },
    balance: 1200,
  },
  {
    id: "2",
    name: "Sunnydale Elementary",
    category: "Primary",
    product: "SchoolPro",
    county: "Sunnydale County",
    registrationDate: new Date("2021-01-20"),
    contactInfo: {
      phone: "555-5678",
      email: "info@sunnydaleelem.edu",
    },
    balance: 850,
  },
  {
    id: "3",
    name: "Riverdale Academy",
    category: "IGCSE",
    product: "ClassTrack",
    county: "Riverdale County",
    registrationDate: new Date("2019-07-01"),
    contactInfo: {
      phone: "555-8765",
      email: "contact@riverdaleacademy.edu",
    },
    balance: 950,
  },
  {
    id: "4",
    name: "Mountainview High",
    category: "Secondary",
    product: "EduSuite",
    county: "Mountainview County",
    registrationDate: new Date("2018-07-05"),
    contactInfo: {
      phone: "555-4321",
      email: "info@mountainviewhigh.edu",
    },
    balance: 1500,
  },
  {
    id: "5",
    name: "Lakeside Middle School",
    category: "Secondary",
    product: "SchoolPro",
    county: "Lakeside County",
    registrationDate: new Date("2021-06-18"),
    contactInfo: {
      phone: "555-7890",
      email: "contact@lakesidemiddle.edu",
    },
    balance: 675,
  },
  {
    id: "6",
    name: "Springfield Primary",
    category: "Primary",
    product: "EduSuite",
    county: "Springfield County",
    registrationDate: new Date("2020-06-22"),
    contactInfo: {
      phone: "555-2345",
      email: "info@springfieldprimary.edu",
    },
    balance: 725,
  },
  {
    id: "7",
    name: "Hilltop High School",
    category: "Secondary",
    product: "ClassTrack",
    county: "Hilltop County",
    registrationDate: new Date("2019-07-10"),
    contactInfo: {
      phone: "555-6543",
      email: "contact@hilltophigh.edu",
    },
    balance: 1100,
  },
  {
    id: "8",
    name: "Cedarwood Academy",
    category: "IGCSE",
    product: "EduSuite",
    county: "Cedarwood County",
    registrationDate: new Date("2018-07-15"),
    contactInfo: {
      phone: "555-8760",
      email: "info@cedarwoodacademy.edu",
    },
    balance: 940,
  },
  {
    id: "9",
    name: "Brookfield Elementary",
    category: "Primary",
    product: "SchoolPro",
    county: "Brookfield County",
    registrationDate: new Date("2021-06-25"),
    contactInfo: {
      phone: "555-5432",
      email: "contact@brookfieldelem.edu",
    },
    balance: 820,
  },
  {
    id: "10",
    name: "Maplewood High",
    category: "Secondary",
    product: "ClassTrack",
    county: "Maplewood County",
    registrationDate: new Date("2021-07-20"),
    contactInfo: {
      phone: "555-0987",
      email: "info@maplewoodhigh.edu",
    },
    balance: 1300,
  },
  {
    id: "11",
    name: "Oakridge High School",
    category: "Secondary",
    product: "EduSuite",
    county: "Oakridge County",
    registrationDate: new Date("2020-08-15"),
    contactInfo: {
      phone: "555-6578",
      email: "contact@oakridgehigh.edu",
    },
    balance: 1500,
  },
  {
    id: "12",
    name: "Pinehill Elementary",
    category: "Primary",
    product: "SchoolPro",
    county: "Pinehill County",
    registrationDate: new Date("2021-09-10"),
    contactInfo: {
      phone: "555-1230",
      email: "info@pinehillelem.edu",
    },
    balance: 680,
  },
  {
    id: "13",
    name: "Elmwood Academy",
    category: "IGCSE",
    product: "ClassTrack",
    county: "Elmwood County",
    registrationDate: new Date("2019-11-12"),
    contactInfo: {
      phone: "555-8764",
      email: "contact@elmwoodacademy.edu",
    },
    balance: 940,
  },
  {
    id: "14",
    name: "Riverside High",
    category: "Secondary",
    product: "EduSuite",
    county: "Riverside County",
    registrationDate: new Date("2018-10-05"),
    contactInfo: {
      phone: "555-4322",
      email: "info@riversidehigh.edu",
    },
    balance: 1200,
  },
  {
    id: "15",
    name: "Sunset Primary",
    category: "Primary",
    product: "SchoolPro",
    county: "Sunset County",
    registrationDate: new Date("2021-12-18"),
    contactInfo: {
      phone: "555-7899",
      email: "contact@sunsetprimary.edu",
    },
    balance: 750,
  },
];

export default data;
